"""Literature Cited (Bates/CBE name-year style). key -> (in-text label, full citation).

Only sources whose bibliographic details are well established are listed. Items whose exact page
numbers / author lists should still be checked against the publisher record are listed in
paper/REFERENCE_CHECKLIST.md (they are NOT silently guessed in the text).
Style: Author(s) Initials. Year. Title in sentence case. Journal abbreviation Volume(issue):pages."""

REFS = {
 "adebayo2018": ("Adebayo et al. 2018",
   "Adebayo J, Gilmer J, Muelly M, Goodfellow I, Hardt M, Kim B. 2018. Sanity checks for saliency maps. Adv Neural Inf Process Syst 31:9505-9515."),
 "albzour2026": ("Albzour 2026",
   "Albzour N. 2026. A leakage-aware comparative benchmark of machine learning, deep learning, and transformer models for reliable leukemia detection. arXiv:2606.24944 (preprint)."),
 "aria2021": ("Aria et al. 2021",
   "Aria M, Ghaderzadeh M, Bashash D, Abolghasemi H, Asadi F, Hosseini A. 2021. Acute lymphoblastic leukemia (ALL) image dataset. Kaggle. doi:10.34740/KAGGLE/DSV/2175623."),
 "benavoli2017": ("Benavoli et al. 2017",
   "Benavoli A, Corani G, Demsar J, Zaffalon M. 2017. Time for a change: a tutorial for comparing multiple classifiers through Bayesian analysis. J Mach Learn Res 18(77):1-36."),
 "bhuiyan2008": ("Bhuiyan et al. 2008",
   "Bhuiyan SMA, Adhami RR, Khan JF. 2008. Fast and adaptive bidimensional empirical mode decomposition using order-statistic filter based envelope estimation. EURASIP J Adv Signal Process 2008:728356."),
 "bradski2000": ("Bradski 2000",
   "Bradski G. 2000. The OpenCV library. Dr Dobbs J Softw Tools 25(11):120-125."),
 "degrave2021": ("DeGrave et al. 2021",
   "DeGrave AJ, Janizek JD, Lee SI. 2021. AI for radiographic COVID-19 detection selects shortcuts over signal. Nat Mach Intell 3:610-619."),
 "demsar2006": ("Demsar 2006",
   "Demsar J. 2006. Statistical comparisons of classifiers over multiple data sets. J Mach Learn Res 7:1-30."),
 "dosovitskiy2021": ("Dosovitskiy et al. 2021",
   "Dosovitskiy A, Beyer L, Kolesnikov A, Weissenborn D, Zhai X, Unterthiner T, Dehghani M, Minderer M, Heigold G, Gelly S, Uszkoreit J, Houlsby N. 2021. An image is worth 16x16 words: transformers for image recognition at scale. In: Int Conf Learn Represent."),
 "efron1979": ("Efron 1979",
   "Efron B. 1979. Bootstrap methods: another look at the jackknife. Ann Stat 7(1):1-26."),
 "field2007": ("Field and Welsh 2007",
   "Field CA, Welsh AH. 2007. Bootstrapping clustered data. J R Stat Soc Ser B 69(3):369-390."),
 "frangi1998": ("Frangi et al. 1998",
   "Frangi AF, Niessen WJ, Vincken KL, Viergever MA. 1998. Multiscale vessel enhancement filtering. In: Medical Image Computing and Computer-Assisted Intervention. Lecture Notes in Computer Science vol 1496. Berlin: Springer. p 130-137."),
 "geirhos2020": ("Geirhos et al. 2020",
   "Geirhos R, Jacobsen JH, Michaelis C, Zemel R, Brendel W, Bethge M, Wichmann FA. 2020. Shortcut learning in deep neural networks. Nat Mach Intell 2:665-673."),
 "ghaderzadeh2022": ("Ghaderzadeh et al. 2022",
   "Ghaderzadeh M, Aria M, Hosseini A, Asadi F, Bashash D, Abolghasemi H. 2022. A fast and efficient CNN model for B-ALL diagnosis and its subtypes classification using peripheral blood smear images. Int J Intell Syst 37(8):5113-5133."),
 "guo2017": ("Guo et al. 2017",
   "Guo C, Pleiss G, Sun Y, Weinberger KQ. 2017. On calibration of modern neural networks. Proc Mach Learn Res 70:1321-1330."),
 "haralick1973": ("Haralick et al. 1973",
   "Haralick RM, Shanmugam K, Dinstein I. 1973. Textural features for image classification. IEEE Trans Syst Man Cybern 3(6):610-621."),
 "he2016": ("He et al. 2016",
   "He K, Zhang X, Ren S, Sun J. 2016. Deep residual learning for image recognition. In: Proc IEEE Conf Comput Vis Pattern Recognit. p 770-778."),
 "holm1979": ("Holm 1979",
   "Holm S. 1979. A simple sequentially rejective multiple test procedure. Scand J Stat 6(2):65-70."),
 "hu2022": ("Hu et al. 2022",
   "Hu EJ, Shen Y, Wallis P, Allen-Zhu Z, Li Y, Wang S, Wang L, Chen W. 2022. LoRA: low-rank adaptation of large language models. In: Int Conf Learn Represent."),
 "huang1998": ("Huang et al. 1998",
   "Huang NE, Shen Z, Long SR, Wu MC, Shih HH, Zheng Q, Yen NC, Tung CC, Liu HH. 1998. The empirical mode decomposition and the Hilbert spectrum for nonlinear and non-stationary time series analysis. Proc R Soc Lond A 454:903-995."),
 "ilse2018": ("Ilse et al. 2018",
   "Ilse M, Tomczak JM, Welling M. 2018. Attention-based deep multiple instance learning. Proc Mach Learn Res 80:2127-2136."),
 "kapoor2023": ("Kapoor and Narayanan 2023",
   "Kapoor S, Narayanan A. 2023. Leakage and the reproducibility crisis in machine-learning-based science. Patterns 4(9):100804."),
 "koch2024": ("Koch et al. 2024",
   "Koch V, Wagner SJ, Kazeminia S, Sancar E, Hehr M, Schnabel JA, Peng T, Marr C. 2024. DinoBloom: a foundation model for generalizable cell embeddings in hematology. In: Medical Image Computing and Computer-Assisted Intervention. Cham: Springer. arXiv:2404.05022."),
 "kouzehkanan2022": ("Kouzehkanan et al. 2022",
   "Kouzehkanan ZM, Saghari S, Tavakoli E, Rostami P, Abaszadeh M, Mirzadeh F, Satlsar ES, Gheidishahran M, Gorgi F, Mohammadi S, Hosseini R. 2022. A large dataset of white blood cells containing cell locations and types, along with segmented nuclei and cytoplasm. Sci Rep 12:1123."),
 "labati2011": ("Labati et al. 2011",
   "Labati RD, Piuri V, Scotti F. 2011. All-IDB: the acute lymphoblastic leukemia image database for image processing. In: Proc 18th IEEE Int Conf Image Process. p 2045-2048."),
 "loshchilov2019": ("Loshchilov and Hutter 2019",
   "Loshchilov I, Hutter F. 2019. Decoupled weight decay regularization. In: Int Conf Learn Represent."),
 "matek2019": ("Matek et al. 2019",
   "Matek C, Schwarz S, Spiekermann K, Marr C. 2019. Human-level recognition of blast cells in acute myeloid leukaemia with convolutional neural networks. Nat Mach Intell 1:538-544."),
 "mourya2019": ("Mourya et al. 2019",
   "Mourya S, Kant S, Kumar P, Gupta A, Gupta R. 2019. ALL challenge dataset of ISBI 2019 (C-NMC 2019). The Cancer Imaging Archive. doi:10.7937/tcia.2019.dc64i46r."),
 "nadeau2003": ("Nadeau and Bengio 2003",
   "Nadeau C, Bengio Y. 2003. Inference for the generalization error. Mach Learn 52(3):239-281."),
 "oquab2024": ("Oquab et al. 2024",
   "Oquab M, Darcet T, Moutakanni T, Vo H, Szafraniec M, Khalidov V, Fernandez P, Haziza D, Massa F, El-Nouby A, Assran M, Ballas N, Galuba W, Howes R, Huang PY, Li SW, Misra I, Rabbat M, Sharma V, Synnaeve G, Xu H, Jegou H, Mairal J, Labatut P, Joulin A, Bojanowski P. 2024. DINOv2: learning robust visual features without supervision. Trans Mach Learn Res."),
 "otsu1979": ("Otsu 1979",
   "Otsu N. 1979. A threshold selection method from gray-level histograms. IEEE Trans Syst Man Cybern 9(1):62-66."),
 "paszke2019": ("Paszke et al. 2019",
   "Paszke A, Gross S, Massa F, Lerer A, Bradbury J, Chanan G, Killeen T, Lin Z, Gimelshein N, Antiga L, Desmaison A, Kopf A, Yang E, DeVito Z, Raison M, Tejani A, Chilamkurthy S, Steiner B, Fang L, Bai J, Chintala S. 2019. PyTorch: an imperative style, high-performance deep learning library. Adv Neural Inf Process Syst 32:8024-8035."),
 "pedregosa2011": ("Pedregosa et al. 2011",
   "Pedregosa F, Varoquaux G, Gramfort A, Michel V, Thirion B, Grisel O, Blondel M, Prettenhofer P, Weiss R, Dubourg V, Vanderplas J, Passos A, Cournapeau D, Brucher M, Perrot M, Duchesnay E. 2011. Scikit-learn: machine learning in Python. J Mach Learn Res 12:2825-2830."),
 "perona1990": ("Perona and Malik 1990",
   "Perona P, Malik J. 1990. Scale-space and edge detection using anisotropic diffusion. IEEE Trans Pattern Anal Mach Intell 12(7):629-639."),
 "reinhard2001": ("Reinhard et al. 2001",
   "Reinhard E, Adhikhmin M, Gooch B, Shirley P. 2001. Color transfer between images. IEEE Comput Graph Appl 21(5):34-41."),
 "roberts2017": ("Roberts et al. 2017",
   "Roberts DR, Bahn V, Ciuti S, Boyce MS, Elith J, Guillera-Arroita G, Hauenstein S, Lahoz-Monfort JJ, Schroder B, Thuiller W, Warton DI, Wintle BA, Hartig F, Dormann CF. 2017. Cross-validation strategies for data with temporal, spatial, hierarchical, or phylogenetic structure. Ecography 40(8):913-929."),
 "selvaraju2017": ("Selvaraju et al. 2017",
   "Selvaraju RR, Cogswell M, Das A, Vedantam R, Parikh D, Batra D. 2017. Grad-CAM: visual explanations from deep networks via gradient-based localization. In: Proc IEEE Int Conf Comput Vis. p 618-626."),
 "tan2019": ("Tan and Le 2019",
   "Tan M, Le QV. 2019. EfficientNet: rethinking model scaling for convolutional neural networks. Proc Mach Learn Res 97:6105-6114."),
 "tellez2019": ("Tellez et al. 2019",
   "Tellez D, Litjens G, Bandi P, Bulten W, Bokhorst JM, Ciompi F, van der Laak J. 2019. Quantifying the effects of data augmentation and stain color normalization in convolutional neural networks for computational pathology. Med Image Anal 58:101544."),
 "tomasi1998": ("Tomasi and Manduchi 1998",
   "Tomasi C, Manduchi R. 1998. Bilateral filtering for gray and color images. In: Proc 6th Int Conf Comput Vis. p 839-846."),
 "vanderwalt2014": ("van der Walt et al. 2014",
   "van der Walt S, Schonberger JL, Nunez-Iglesias J, Boulogne F, Warner JD, Yager N, Gouillart E, Yu T. 2014. scikit-image: image processing in Python. PeerJ 2:e453."),
 "wightman2019": ("Wightman 2019",
   "Wightman R. 2019. PyTorch image models. GitHub repository, https://github.com/huggingface/pytorch-image-models."),
 "wu2009": ("Wu and Huang 2009",
   "Wu Z, Huang NE. 2009. Ensemble empirical mode decomposition: a noise-assisted data analysis method. Adv Adapt Data Anal 1(1):1-41."),
}


def sorted_refs(used=None):
    keys = sorted(REFS, key=lambda k: REFS[k][1].lower())
    return [REFS[k][1] for k in keys if used is None or k in used]
